/* Auto-generated by genmsg_cpp for file /home/ece/ros_ws/src/foo_msgs/msg/Control.msg */
#ifndef FOO_MSGS_MESSAGE_CONTROL_H
#define FOO_MSGS_MESSAGE_CONTROL_H
#include <string>
#include <vector>
#include <map>
#include <ostream>
#include "ros/serialization.h"
#include "ros/builtin_message_traits.h"
#include "ros/message_operations.h"
#include "ros/time.h"

#include "ros/macros.h"

#include "ros/assert.h"


namespace foo_msgs
{
template <class ContainerAllocator>
struct Control_ {
  typedef Control_<ContainerAllocator> Type;

  Control_()
  : name()
  , phi(0.0)
  , theta(0.0)
  , psi(0.0)
  , alt(0.0)
  {
  }

  Control_(const ContainerAllocator& _alloc)
  : name(_alloc)
  , phi(0.0)
  , theta(0.0)
  , psi(0.0)
  , alt(0.0)
  {
  }

  typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _name_type;
  std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  name;

  typedef double _phi_type;
  double phi;

  typedef double _theta_type;
  double theta;

  typedef double _psi_type;
  double psi;

  typedef double _alt_type;
  double alt;


  typedef boost::shared_ptr< ::foo_msgs::Control_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::foo_msgs::Control_<ContainerAllocator>  const> ConstPtr;
  boost::shared_ptr<std::map<std::string, std::string> > __connection_header;
}; // struct Control
typedef  ::foo_msgs::Control_<std::allocator<void> > Control;

typedef boost::shared_ptr< ::foo_msgs::Control> ControlPtr;
typedef boost::shared_ptr< ::foo_msgs::Control const> ControlConstPtr;


template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const  ::foo_msgs::Control_<ContainerAllocator> & v)
{
  ros::message_operations::Printer< ::foo_msgs::Control_<ContainerAllocator> >::stream(s, "", v);
  return s;}

} // namespace foo_msgs

namespace ros
{
namespace message_traits
{
template<class ContainerAllocator> struct IsMessage< ::foo_msgs::Control_<ContainerAllocator> > : public TrueType {};
template<class ContainerAllocator> struct IsMessage< ::foo_msgs::Control_<ContainerAllocator>  const> : public TrueType {};
template<class ContainerAllocator>
struct MD5Sum< ::foo_msgs::Control_<ContainerAllocator> > {
  static const char* value() 
  {
    return "5dc2f34b8cef53951d12f6cf2d480fc4";
  }

  static const char* value(const  ::foo_msgs::Control_<ContainerAllocator> &) { return value(); } 
  static const uint64_t static_value1 = 0x5dc2f34b8cef5395ULL;
  static const uint64_t static_value2 = 0x1d12f6cf2d480fc4ULL;
};

template<class ContainerAllocator>
struct DataType< ::foo_msgs::Control_<ContainerAllocator> > {
  static const char* value() 
  {
    return "foo_msgs/Control";
  }

  static const char* value(const  ::foo_msgs::Control_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct Definition< ::foo_msgs::Control_<ContainerAllocator> > {
  static const char* value() 
  {
    return "string name\n\
\n\
float64 phi\n\
\n\
float64 theta\n\
\n\
float64 psi\n\
\n\
float64 alt\n\
\n\
\n\
\n\
";
  }

  static const char* value(const  ::foo_msgs::Control_<ContainerAllocator> &) { return value(); } 
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

template<class ContainerAllocator> struct Serializer< ::foo_msgs::Control_<ContainerAllocator> >
{
  template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
  {
    stream.next(m.name);
    stream.next(m.phi);
    stream.next(m.theta);
    stream.next(m.psi);
    stream.next(m.alt);
  }

  ROS_DECLARE_ALLINONE_SERIALIZER;
}; // struct Control_
} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::foo_msgs::Control_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const  ::foo_msgs::Control_<ContainerAllocator> & v) 
  {
    s << indent << "name: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.name);
    s << indent << "phi: ";
    Printer<double>::stream(s, indent + "  ", v.phi);
    s << indent << "theta: ";
    Printer<double>::stream(s, indent + "  ", v.theta);
    s << indent << "psi: ";
    Printer<double>::stream(s, indent + "  ", v.psi);
    s << indent << "alt: ";
    Printer<double>::stream(s, indent + "  ", v.alt);
  }
};


} // namespace message_operations
} // namespace ros

#endif // FOO_MSGS_MESSAGE_CONTROL_H

