(cl:in-package risc_msgs-msg)
(cl:export '(NAME-VAL
          NAME
          VISIBLE-VAL
          VISIBLE
          X-VAL
          X
          Y-VAL
          Y
          Z-VAL
          Z
          U-VAL
          U
          V-VAL
          V
          W-VAL
          W
          PHI-VAL
          PHI
          THETA-VAL
          THETA
          PSI-VAL
          PSI
          P-VAL
          P
          Q-VAL
          Q
          R-VAL
          R
))