
(cl:in-package :asdf)

(defsystem "foo_msgs-msg"
  :depends-on (:roslisp-msg-protocol :roslisp-utils :std_msgs-msg
)
  :components ((:file "_package")
    (:file "Mocap_data" :depends-on ("_package_Mocap_data"))
    (:file "_package_Mocap_data" :depends-on ("_package"))
    (:file "Trajectory" :depends-on ("_package_Trajectory"))
    (:file "_package_Trajectory" :depends-on ("_package"))
    (:file "Mocap_marker" :depends-on ("_package_Mocap_marker"))
    (:file "_package_Mocap_marker" :depends-on ("_package"))
    (:file "Angle" :depends-on ("_package_Angle"))
    (:file "_package_Angle" :depends-on ("_package"))
    (:file "Risc_rois" :depends-on ("_package_Risc_rois"))
    (:file "_package_Risc_rois" :depends-on ("_package"))
    (:file "Cortex" :depends-on ("_package_Cortex"))
    (:file "_package_Cortex" :depends-on ("_package"))
    (:file "Landmarks" :depends-on ("_package_Landmarks"))
    (:file "_package_Landmarks" :depends-on ("_package"))
    (:file "Control" :depends-on ("_package_Control"))
    (:file "_package_Control" :depends-on ("_package"))
    (:file "Observed_angles" :depends-on ("_package_Observed_angles"))
    (:file "_package_Observed_angles" :depends-on ("_package"))
    (:file "Trajectories" :depends-on ("_package_Trajectories"))
    (:file "_package_Trajectories" :depends-on ("_package"))
    (:file "Waypoints" :depends-on ("_package_Waypoints"))
    (:file "_package_Waypoints" :depends-on ("_package"))
    (:file "Risc_roi" :depends-on ("_package_Risc_roi"))
    (:file "_package_Risc_roi" :depends-on ("_package"))
    (:file "Mocap_markers" :depends-on ("_package_Mocap_markers"))
    (:file "_package_Mocap_markers" :depends-on ("_package"))
    (:file "PendulumStates" :depends-on ("_package_PendulumStates"))
    (:file "_package_PendulumStates" :depends-on ("_package"))
    (:file "Angles" :depends-on ("_package_Angles"))
    (:file "_package_Angles" :depends-on ("_package"))
    (:file "Waypoint" :depends-on ("_package_Waypoint"))
    (:file "_package_Waypoint" :depends-on ("_package"))
    (:file "Observed_rois" :depends-on ("_package_Observed_rois"))
    (:file "_package_Observed_rois" :depends-on ("_package"))
    (:file "Landmark" :depends-on ("_package_Landmark"))
    (:file "_package_Landmark" :depends-on ("_package"))
    (:file "Controls" :depends-on ("_package_Controls"))
    (:file "_package_Controls" :depends-on ("_package"))
    (:file "States" :depends-on ("_package_States"))
    (:file "_package_States" :depends-on ("_package"))
  ))