# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainform.ui'
#
# Created: Fri Aug  1 15:44:49 2014
#      by: PyQt4 UI code generator 4.9.1
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    _fromUtf8 = lambda s: s

class Ui_mainDialog(object):
    def setupUi(self, mainDialog):
        mainDialog.setObjectName(_fromUtf8("mainDialog"))
        mainDialog.resize(659, 887)
        self.verticalLayoutWidget = QtGui.QWidget(mainDialog)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(490, 10, 151, 95))
        self.verticalLayoutWidget.setObjectName(_fromUtf8("verticalLayoutWidget"))
        self.verticalLayout = QtGui.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setSpacing(6)
        self.verticalLayout.setMargin(0)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.landButton = QtGui.QPushButton(self.verticalLayoutWidget)
        self.landButton.setObjectName(_fromUtf8("landButton"))
        self.verticalLayout.addWidget(self.landButton)
        self.emergencyButton = QtGui.QPushButton(self.verticalLayoutWidget)
        self.emergencyButton.setObjectName(_fromUtf8("emergencyButton"))
        self.verticalLayout.addWidget(self.emergencyButton)
        self.takeoffButton = QtGui.QPushButton(self.verticalLayoutWidget)
        self.takeoffButton.setObjectName(_fromUtf8("takeoffButton"))
        self.verticalLayout.addWidget(self.takeoffButton)
        self.verticalLayoutWidget_2 = QtGui.QWidget(mainDialog)
        self.verticalLayoutWidget_2.setGeometry(QtCore.QRect(10, 10, 466, 861))
        self.verticalLayoutWidget_2.setObjectName(_fromUtf8("verticalLayoutWidget_2"))
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.verticalLayoutWidget_2)
        self.verticalLayout_2.setMargin(0)
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setSpacing(6)
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.quad1Button = QtGui.QPushButton(self.verticalLayoutWidget_2)
        self.quad1Button.setCheckable(True)
        self.quad1Button.setChecked(True)
        self.quad1Button.setFlat(False)
        self.quad1Button.setObjectName(_fromUtf8("quad1Button"))
        self.horizontalLayout.addWidget(self.quad1Button)
        self.quad2Button = QtGui.QPushButton(self.verticalLayoutWidget_2)
        self.quad2Button.setCheckable(True)
        self.quad2Button.setObjectName(_fromUtf8("quad2Button"))
        self.horizontalLayout.addWidget(self.quad2Button)
        self.quad3Button = QtGui.QPushButton(self.verticalLayoutWidget_2)
        self.quad3Button.setCheckable(True)
        self.quad3Button.setObjectName(_fromUtf8("quad3Button"))
        self.horizontalLayout.addWidget(self.quad3Button)
        self.quad4Button = QtGui.QPushButton(self.verticalLayoutWidget_2)
        self.quad4Button.setCheckable(True)
        self.quad4Button.setObjectName(_fromUtf8("quad4Button"))
        self.horizontalLayout.addWidget(self.quad4Button)
        self.allQuadButton = QtGui.QPushButton(self.verticalLayoutWidget_2)
        self.allQuadButton.setCheckable(True)
        self.allQuadButton.setObjectName(_fromUtf8("allQuadButton"))
        self.horizontalLayout.addWidget(self.allQuadButton)
        self.verticalLayout_2.addLayout(self.horizontalLayout)
        self.label = QtGui.QLabel(self.verticalLayoutWidget_2)
        self.label.setObjectName(_fromUtf8("label"))
        self.verticalLayout_2.addWidget(self.label)
        self.rostopicCombo = QtGui.QComboBox(self.verticalLayoutWidget_2)
        self.rostopicCombo.setObjectName(_fromUtf8("rostopicCombo"))
        self.rostopicCombo.addItem(_fromUtf8(""))
        self.rostopicCombo.addItem(_fromUtf8(""))
        self.rostopicCombo.addItem(_fromUtf8(""))
        self.rostopicCombo.addItem(_fromUtf8(""))
        self.rostopicCombo.addItem(_fromUtf8(""))
        self.verticalLayout_2.addWidget(self.rostopicCombo)
        self.rostopicDisplay = QtGui.QTextBrowser(self.verticalLayoutWidget_2)
        self.rostopicDisplay.setObjectName(_fromUtf8("rostopicDisplay"))
        self.verticalLayout_2.addWidget(self.rostopicDisplay)
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setSpacing(6)
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.label_2 = QtGui.QLabel(self.verticalLayoutWidget_2)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.horizontalLayout_2.addWidget(self.label_2)
        self.batteryBar = QtGui.QProgressBar(self.verticalLayoutWidget_2)
        self.batteryBar.setProperty("value", 0)
        self.batteryBar.setObjectName(_fromUtf8("batteryBar"))
        self.horizontalLayout_2.addWidget(self.batteryBar)
        self.verticalLayout_2.addLayout(self.horizontalLayout_2)
        self.groupBox = QtGui.QGroupBox(mainDialog)
        self.groupBox.setGeometry(QtCore.QRect(490, 110, 101, 169))
        self.groupBox.setFlat(False)
        self.groupBox.setObjectName(_fromUtf8("groupBox"))
        self.verticalLayoutWidget_3 = QtGui.QWidget(self.groupBox)
        self.verticalLayoutWidget_3.setGeometry(QtCore.QRect(0, 30, 102, 136))
        self.verticalLayoutWidget_3.setObjectName(_fromUtf8("verticalLayoutWidget_3"))
        self.verticalLayout_3 = QtGui.QVBoxLayout(self.verticalLayoutWidget_3)
        self.verticalLayout_3.setMargin(0)
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        self.joystickRadioButton = QtGui.QRadioButton(self.verticalLayoutWidget_3)
        self.joystickRadioButton.setEnabled(True)
        self.joystickRadioButton.setChecked(True)
        self.joystickRadioButton.setObjectName(_fromUtf8("joystickRadioButton"))
        self.verticalLayout_3.addWidget(self.joystickRadioButton)
        self.controllerRadioButton = QtGui.QRadioButton(self.verticalLayoutWidget_3)
        self.controllerRadioButton.setEnabled(True)
        self.controllerRadioButton.setChecked(False)
        self.controllerRadioButton.setAutoRepeat(False)
        self.controllerRadioButton.setObjectName(_fromUtf8("controllerRadioButton"))
        self.verticalLayout_3.addWidget(self.controllerRadioButton)
        self.layoutWidget = QtGui.QWidget(mainDialog)
        self.layoutWidget.setGeometry(QtCore.QRect(490, 300, 153, 61))
        self.layoutWidget.setObjectName(_fromUtf8("layoutWidget"))
        self.verticalLayout_4 = QtGui.QVBoxLayout(self.layoutWidget)
        self.verticalLayout_4.setMargin(0)
        self.verticalLayout_4.setObjectName(_fromUtf8("verticalLayout_4"))
        self.waypointDesignerButton = QtGui.QPushButton(self.layoutWidget)
        self.waypointDesignerButton.setObjectName(_fromUtf8("waypointDesignerButton"))
        self.verticalLayout_4.addWidget(self.waypointDesignerButton)
        self.publishWaypointCheckBox = QtGui.QCheckBox(self.layoutWidget)
        self.publishWaypointCheckBox.setObjectName(_fromUtf8("publishWaypointCheckBox"))
        self.verticalLayout_4.addWidget(self.publishWaypointCheckBox)
        self.rvizButton = QtGui.QPushButton(mainDialog)
        self.rvizButton.setGeometry(QtCore.QRect(510, 390, 121, 27))
        self.rvizButton.setObjectName(_fromUtf8("rvizButton"))

        self.retranslateUi(mainDialog)
        QtCore.QMetaObject.connectSlotsByName(mainDialog)

    def retranslateUi(self, mainDialog):
        mainDialog.setWindowTitle(QtGui.QApplication.translate("mainDialog", "AR Drone Control Center", None, QtGui.QApplication.UnicodeUTF8))
        self.landButton.setText(QtGui.QApplication.translate("mainDialog", "Land", None, QtGui.QApplication.UnicodeUTF8))
        self.emergencyButton.setText(QtGui.QApplication.translate("mainDialog", "Emergency", None, QtGui.QApplication.UnicodeUTF8))
        self.takeoffButton.setText(QtGui.QApplication.translate("mainDialog", "Takeoff", None, QtGui.QApplication.UnicodeUTF8))
        self.quad1Button.setText(QtGui.QApplication.translate("mainDialog", "Quad 1", None, QtGui.QApplication.UnicodeUTF8))
        self.quad2Button.setText(QtGui.QApplication.translate("mainDialog", "Quad 2", None, QtGui.QApplication.UnicodeUTF8))
        self.quad3Button.setText(QtGui.QApplication.translate("mainDialog", "Quad 3", None, QtGui.QApplication.UnicodeUTF8))
        self.quad4Button.setText(QtGui.QApplication.translate("mainDialog", "Quad 4", None, QtGui.QApplication.UnicodeUTF8))
        self.allQuadButton.setText(QtGui.QApplication.translate("mainDialog", "All", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("mainDialog", "ROS topics:", None, QtGui.QApplication.UnicodeUTF8))
        self.rostopicCombo.setItemText(0, QtGui.QApplication.translate("mainDialog", "navdata", None, QtGui.QApplication.UnicodeUTF8))
        self.rostopicCombo.setItemText(1, QtGui.QApplication.translate("mainDialog", "imu", None, QtGui.QApplication.UnicodeUTF8))
        self.rostopicCombo.setItemText(2, QtGui.QApplication.translate("mainDialog", "mag", None, QtGui.QApplication.UnicodeUTF8))
        self.rostopicCombo.setItemText(3, QtGui.QApplication.translate("mainDialog", "camera_info", None, QtGui.QApplication.UnicodeUTF8))
        self.rostopicCombo.setItemText(4, QtGui.QApplication.translate("mainDialog", "cortex", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setText(QtGui.QApplication.translate("mainDialog", "Battery:", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox.setTitle(QtGui.QApplication.translate("mainDialog", "Controller", None, QtGui.QApplication.UnicodeUTF8))
        self.joystickRadioButton.setText(QtGui.QApplication.translate("mainDialog", "Joystick", None, QtGui.QApplication.UnicodeUTF8))
        self.controllerRadioButton.setText(QtGui.QApplication.translate("mainDialog", "Controller", None, QtGui.QApplication.UnicodeUTF8))
        self.waypointDesignerButton.setText(QtGui.QApplication.translate("mainDialog", "Waypoint designer", None, QtGui.QApplication.UnicodeUTF8))
        self.publishWaypointCheckBox.setText(QtGui.QApplication.translate("mainDialog", "Publish waypoints", None, QtGui.QApplication.UnicodeUTF8))
        self.rvizButton.setText(QtGui.QApplication.translate("mainDialog", "RViz", None, QtGui.QApplication.UnicodeUTF8))

