/* Auto-generated by genmsg_cpp for file /home/ece/ros_ws/src/foo_msgs/msg/Angles.msg */
#ifndef FOO_MSGS_MESSAGE_ANGLES_H
#define FOO_MSGS_MESSAGE_ANGLES_H
#include <string>
#include <vector>
#include <map>
#include <ostream>
#include "ros/serialization.h"
#include "ros/builtin_message_traits.h"
#include "ros/message_operations.h"
#include "ros/time.h"

#include "ros/macros.h"

#include "ros/assert.h"

#include "foo_msgs/Angle.h"
#include "foo_msgs/Angle.h"

namespace foo_msgs
{
template <class ContainerAllocator>
struct Angles_ {
  typedef Angles_<ContainerAllocator> Type;

  Angles_()
  : name()
  , landmarks()
  , quads()
  {
  }

  Angles_(const ContainerAllocator& _alloc)
  : name(_alloc)
  , landmarks(_alloc)
  , quads(_alloc)
  {
  }

  typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _name_type;
  std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  name;

  typedef std::vector< ::foo_msgs::Angle_<ContainerAllocator> , typename ContainerAllocator::template rebind< ::foo_msgs::Angle_<ContainerAllocator> >::other >  _landmarks_type;
  std::vector< ::foo_msgs::Angle_<ContainerAllocator> , typename ContainerAllocator::template rebind< ::foo_msgs::Angle_<ContainerAllocator> >::other >  landmarks;

  typedef std::vector< ::foo_msgs::Angle_<ContainerAllocator> , typename ContainerAllocator::template rebind< ::foo_msgs::Angle_<ContainerAllocator> >::other >  _quads_type;
  std::vector< ::foo_msgs::Angle_<ContainerAllocator> , typename ContainerAllocator::template rebind< ::foo_msgs::Angle_<ContainerAllocator> >::other >  quads;


  typedef boost::shared_ptr< ::foo_msgs::Angles_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::foo_msgs::Angles_<ContainerAllocator>  const> ConstPtr;
  boost::shared_ptr<std::map<std::string, std::string> > __connection_header;
}; // struct Angles
typedef  ::foo_msgs::Angles_<std::allocator<void> > Angles;

typedef boost::shared_ptr< ::foo_msgs::Angles> AnglesPtr;
typedef boost::shared_ptr< ::foo_msgs::Angles const> AnglesConstPtr;


template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const  ::foo_msgs::Angles_<ContainerAllocator> & v)
{
  ros::message_operations::Printer< ::foo_msgs::Angles_<ContainerAllocator> >::stream(s, "", v);
  return s;}

} // namespace foo_msgs

namespace ros
{
namespace message_traits
{
template<class ContainerAllocator> struct IsMessage< ::foo_msgs::Angles_<ContainerAllocator> > : public TrueType {};
template<class ContainerAllocator> struct IsMessage< ::foo_msgs::Angles_<ContainerAllocator>  const> : public TrueType {};
template<class ContainerAllocator>
struct MD5Sum< ::foo_msgs::Angles_<ContainerAllocator> > {
  static const char* value() 
  {
    return "9dd576705f18c801e12e4a78c9c66088";
  }

  static const char* value(const  ::foo_msgs::Angles_<ContainerAllocator> &) { return value(); } 
  static const uint64_t static_value1 = 0x9dd576705f18c801ULL;
  static const uint64_t static_value2 = 0xe12e4a78c9c66088ULL;
};

template<class ContainerAllocator>
struct DataType< ::foo_msgs::Angles_<ContainerAllocator> > {
  static const char* value() 
  {
    return "foo_msgs/Angles";
  }

  static const char* value(const  ::foo_msgs::Angles_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct Definition< ::foo_msgs::Angles_<ContainerAllocator> > {
  static const char* value() 
  {
    return "string name\n\
Angle[] landmarks\n\
Angle[] quads\n\
\n\
================================================================================\n\
MSG: foo_msgs/Angle\n\
string name\n\
bool visible\n\
float64 azim\n\
float64 elev\n\
\n\
";
  }

  static const char* value(const  ::foo_msgs::Angles_<ContainerAllocator> &) { return value(); } 
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

template<class ContainerAllocator> struct Serializer< ::foo_msgs::Angles_<ContainerAllocator> >
{
  template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
  {
    stream.next(m.name);
    stream.next(m.landmarks);
    stream.next(m.quads);
  }

  ROS_DECLARE_ALLINONE_SERIALIZER;
}; // struct Angles_
} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::foo_msgs::Angles_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const  ::foo_msgs::Angles_<ContainerAllocator> & v) 
  {
    s << indent << "name: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.name);
    s << indent << "landmarks[]" << std::endl;
    for (size_t i = 0; i < v.landmarks.size(); ++i)
    {
      s << indent << "  landmarks[" << i << "]: ";
      s << std::endl;
      s << indent;
      Printer< ::foo_msgs::Angle_<ContainerAllocator> >::stream(s, indent + "    ", v.landmarks[i]);
    }
    s << indent << "quads[]" << std::endl;
    for (size_t i = 0; i < v.quads.size(); ++i)
    {
      s << indent << "  quads[" << i << "]: ";
      s << std::endl;
      s << indent;
      Printer< ::foo_msgs::Angle_<ContainerAllocator> >::stream(s, indent + "    ", v.quads[i]);
    }
  }
};


} // namespace message_operations
} // namespace ros

#endif // FOO_MSGS_MESSAGE_ANGLES_H

