/* Auto-generated by genmsg_cpp for file /home/ece/ros_ws/src/foo_msgs/msg/Observed_angles.msg */
#ifndef FOO_MSGS_MESSAGE_OBSERVED_ANGLES_H
#define FOO_MSGS_MESSAGE_OBSERVED_ANGLES_H
#include <string>
#include <vector>
#include <map>
#include <ostream>
#include "ros/serialization.h"
#include "ros/builtin_message_traits.h"
#include "ros/message_operations.h"
#include "ros/time.h"

#include "ros/macros.h"

#include "ros/assert.h"

#include "std_msgs/Header.h"
#include "foo_msgs/Angles.h"

namespace foo_msgs
{
template <class ContainerAllocator>
struct Observed_angles_ {
  typedef Observed_angles_<ContainerAllocator> Type;

  Observed_angles_()
  : header()
  , Obj()
  {
  }

  Observed_angles_(const ContainerAllocator& _alloc)
  : header(_alloc)
  , Obj(_alloc)
  {
  }

  typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
   ::std_msgs::Header_<ContainerAllocator>  header;

  typedef std::vector< ::foo_msgs::Angles_<ContainerAllocator> , typename ContainerAllocator::template rebind< ::foo_msgs::Angles_<ContainerAllocator> >::other >  _Obj_type;
  std::vector< ::foo_msgs::Angles_<ContainerAllocator> , typename ContainerAllocator::template rebind< ::foo_msgs::Angles_<ContainerAllocator> >::other >  Obj;


  typedef boost::shared_ptr< ::foo_msgs::Observed_angles_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::foo_msgs::Observed_angles_<ContainerAllocator>  const> ConstPtr;
  boost::shared_ptr<std::map<std::string, std::string> > __connection_header;
}; // struct Observed_angles
typedef  ::foo_msgs::Observed_angles_<std::allocator<void> > Observed_angles;

typedef boost::shared_ptr< ::foo_msgs::Observed_angles> Observed_anglesPtr;
typedef boost::shared_ptr< ::foo_msgs::Observed_angles const> Observed_anglesConstPtr;


template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const  ::foo_msgs::Observed_angles_<ContainerAllocator> & v)
{
  ros::message_operations::Printer< ::foo_msgs::Observed_angles_<ContainerAllocator> >::stream(s, "", v);
  return s;}

} // namespace foo_msgs

namespace ros
{
namespace message_traits
{
template<class ContainerAllocator> struct IsMessage< ::foo_msgs::Observed_angles_<ContainerAllocator> > : public TrueType {};
template<class ContainerAllocator> struct IsMessage< ::foo_msgs::Observed_angles_<ContainerAllocator>  const> : public TrueType {};
template<class ContainerAllocator>
struct MD5Sum< ::foo_msgs::Observed_angles_<ContainerAllocator> > {
  static const char* value() 
  {
    return "8b371119782f9b738e9c6225d8efba1c";
  }

  static const char* value(const  ::foo_msgs::Observed_angles_<ContainerAllocator> &) { return value(); } 
  static const uint64_t static_value1 = 0x8b371119782f9b73ULL;
  static const uint64_t static_value2 = 0x8e9c6225d8efba1cULL;
};

template<class ContainerAllocator>
struct DataType< ::foo_msgs::Observed_angles_<ContainerAllocator> > {
  static const char* value() 
  {
    return "foo_msgs/Observed_angles";
  }

  static const char* value(const  ::foo_msgs::Observed_angles_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct Definition< ::foo_msgs::Observed_angles_<ContainerAllocator> > {
  static const char* value() 
  {
    return "Header header\n\
Angles[] Obj\n\
\n\
================================================================================\n\
MSG: std_msgs/Header\n\
# Standard metadata for higher-level stamped data types.\n\
# This is generally used to communicate timestamped data \n\
# in a particular coordinate frame.\n\
# \n\
# sequence ID: consecutively increasing ID \n\
uint32 seq\n\
#Two-integer timestamp that is expressed as:\n\
# * stamp.secs: seconds (stamp_secs) since epoch\n\
# * stamp.nsecs: nanoseconds since stamp_secs\n\
# time-handling sugar is provided by the client library\n\
time stamp\n\
#Frame this data is associated with\n\
# 0: no frame\n\
# 1: global frame\n\
string frame_id\n\
\n\
================================================================================\n\
MSG: foo_msgs/Angles\n\
string name\n\
Angle[] landmarks\n\
Angle[] quads\n\
\n\
================================================================================\n\
MSG: foo_msgs/Angle\n\
string name\n\
bool visible\n\
float64 azim\n\
float64 elev\n\
\n\
";
  }

  static const char* value(const  ::foo_msgs::Observed_angles_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator> struct HasHeader< ::foo_msgs::Observed_angles_<ContainerAllocator> > : public TrueType {};
template<class ContainerAllocator> struct HasHeader< const ::foo_msgs::Observed_angles_<ContainerAllocator> > : public TrueType {};
} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

template<class ContainerAllocator> struct Serializer< ::foo_msgs::Observed_angles_<ContainerAllocator> >
{
  template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
  {
    stream.next(m.header);
    stream.next(m.Obj);
  }

  ROS_DECLARE_ALLINONE_SERIALIZER;
}; // struct Observed_angles_
} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::foo_msgs::Observed_angles_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const  ::foo_msgs::Observed_angles_<ContainerAllocator> & v) 
  {
    s << indent << "header: ";
s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "Obj[]" << std::endl;
    for (size_t i = 0; i < v.Obj.size(); ++i)
    {
      s << indent << "  Obj[" << i << "]: ";
      s << std::endl;
      s << indent;
      Printer< ::foo_msgs::Angles_<ContainerAllocator> >::stream(s, indent + "    ", v.Obj[i]);
    }
  }
};


} // namespace message_operations
} // namespace ros

#endif // FOO_MSGS_MESSAGE_OBSERVED_ANGLES_H

